// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWTWmNA2O-vQiyLevsXlrNECIp6eFKBS0',
    appId: '1:398350121788:web:b5710bddc337fb39107c39',
    messagingSenderId: '398350121788',
    projectId: 'kiddy-65de6',
    authDomain: 'kiddy-65de6.firebaseapp.com',
    databaseURL: 'https://kiddy-65de6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiddy-65de6.appspot.com',
    measurementId: 'G-NGLME023N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGQgWIrPnOgrPKWEqFKEvXHarghZ1y8S4',
    appId: '1:398350121788:android:8326cb2b6af160e5107c39',
    messagingSenderId: '398350121788',
    projectId: 'kiddy-65de6',
    databaseURL: 'https://kiddy-65de6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiddy-65de6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLhNEG1cZWbVien89aJ7DIz0vZJYyl8AQ',
    appId: '1:398350121788:ios:2da34725c6ef37cf107c39',
    messagingSenderId: '398350121788',
    projectId: 'kiddy-65de6',
    databaseURL: 'https://kiddy-65de6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiddy-65de6.appspot.com',
    iosBundleId: 'com.example.kiddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLhNEG1cZWbVien89aJ7DIz0vZJYyl8AQ',
    appId: '1:398350121788:ios:2da34725c6ef37cf107c39',
    messagingSenderId: '398350121788',
    projectId: 'kiddy-65de6',
    databaseURL: 'https://kiddy-65de6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiddy-65de6.appspot.com',
    iosBundleId: 'com.example.kiddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWTWmNA2O-vQiyLevsXlrNECIp6eFKBS0',
    appId: '1:398350121788:web:fed33d66e9d5b2e8107c39',
    messagingSenderId: '398350121788',
    projectId: 'kiddy-65de6',
    authDomain: 'kiddy-65de6.firebaseapp.com',
    databaseURL: 'https://kiddy-65de6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiddy-65de6.appspot.com',
    measurementId: 'G-049Z93B4N9',
  );
}
